# Copyright 2023 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Example Piantor Pro BT'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '[
        "piantor_pro_bt_left", "piantor_pro_bt_right"
      ]'
      #shield: '["nice_view"]'
      alphas: '["QWERTY"]'
      snippet: '["studio-rpc-usb-uart"]'
      cmake_args: '["-DCONFIG_ZMK_STUDIO=y"]'
  # build_right:
  #   uses: ./.github/workflows/main.yml
  #   secrets: inherit
  #   with:
  #     board: '[
  #       "piantor_pro_bt_right"
  #     ]'
  #     #shield: '["nice_view"]'
  #     alphas: "QWERTY"
  #     snippet: '["studio-rpc-usb-uart"]'