# Copyright 2023 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Example Piantor Pro BT left'
on: workflow_dispatch
jobs:
  build_left:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '[
        "piantor_pro_bt_left"
      ]'
      shield: '["nice_view"]'
      snippet: '["studio-rpc-usb-uart"]'
      cmake_args: '["-DCONFIG_ZMK_STUDIO=y"]'