# Copyright 2023 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Example Piantor Pro BT'
on: workflow_dispatch
jobs:
  build_left:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '[
        "piantor_pro_bt_left"
      ]'
      # shield: '["raw_hid_adapter"]' #nice_view doesnt work
      alphas: '["QWERTY"]'
      extra: '["COLEMAKDH"]'
      tap: '["QWERTY"]'
      snippet: '["studio-rpc-usb-uart"]'
      # cmake_args: '["-DCONFIG_ZMK_STUDIO=y"]'

      # kconfig: '["CONFIG_ZMK_POINTING=y\nCONFIG_ZMK_STUDIO=y\n# enable Raw HID module\nCONFIG_RAW_HID=y\n# add additional USB HID device\nCONFIG_USB_HID_DEVICE_COUNT=2"]'
      kconfig: '["CONFIG_ZMK_POINTING=y\nCONFIG_ZMK_STUDIO=y\n"]'

      modules: '["zzeneg/zmk-raw-hid/main srwi/zmk-keypeek-layer-notifier/master"]' #zzeneg/zmk-raw-hid/main

  build_right:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '[
        "piantor_pro_bt_right"
      ]'
      # shield: '["raw_hid_adapter"]' #nice_view doesnt work
      alphas: '["QWERTY"]'
      extra: '["COLEMAKDH"]'
      tap: '["QWERTY"]'
      snippet: '["studio-rpc-usb-uart"]'
      kconfig: '["CONFIG_ZMK_POINTING=y"]'
      # modules: '["zzeneg/zmk-raw-hid/main srwi/zmk-keypeek-layer-notifier/master"]'
  # build_reset:
  #   uses: ./.github/workflows/main.yml
  #   secrets: inherit
  #   with:
  #     board: '[
  #       "piantor_pro_bt_left", 
  #       "piantor_pro_bt_right"
  #     ]'
  #     shield: '["settings_reset"]' #nice_view doesnt work
  #     snippet: '["studio-rpc-usb-uart"]'